name: hw1

on:
  pull_request:
    branches:
      - hw1

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
          os: [ubuntu-18.04]

        fail-fast: false

    steps:

    - name: setup
      run: echo "::add-path::${HOME}/opt/conda/bin"

    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: dependency (ubuntu)
      if: matrix.os != 'macos-latest'
      run: |
        sudo apt-get -qy install python

    - name: grade
      run: |
        username=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 1)
        echo "cd hw1/$username"
        cd hw1/$username
        ../validate.sh
